#!/bin/sh
#
# Copyright (C) 2016 Red Hat, Inc.
#
# This file is part of openconnect.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# This test uses LD_PRELOAD
PRELOAD=1
SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
top_builddir=${top_builddir:-..}

. `dirname $0`/common.sh

hwtpm_list=${hwtpm_list:-`echo ${certdir}/swtpm*-key-tpm.pem`}

echo "Testing TPMv2 auth with hwtpm..."

launch_simple_sr_server -d 1 -f -c configs/test-user-cert.config
PID=$!
wait_server $PID

export TPM_INTERFACE_TYPE=dev

for KEY in ${hwtpm_list}; do
    echo -n "Connecting to obtain cookie (with key ${KEY##*/})... "
    if [ "${KEY%%.p12}" != "${KEY}" ]; then
	CERTARGS="-c ${KEY} --key-password password"
    else
	CERT="${KEY%-key-*.pem}-cert.pem"
	if [ ! -r "$CERT" ]; then CERT="${certdir}/$CERT"; fi
	CERTARGS="--sslkey ${KEY} -c ${CERT}"
    fi
    if ! echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:443 -u test $CERTARGS --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly -vvvvv --passwd-on-stdin; then
	fail $PID "Could not connect with key ${KEY##*/}!"
    fi
done

echo ok

cleanup

exit 0
